<?php
include("code/conn.php");
// session_start();
                                        if($_GET['oid']==""){
                                            echo "<script>window.location='index.php'</script>";
                                        }
                                        $oid=$_GET['oid'];

                                        $s="SELECT * FROM `orders` where id=$oid";
                                        $q=mysqli_query($con,$s);
                                        $f_r=mysqli_fetch_array($q);
                                        $uid=$_SESSION['uid'];

                                        $ss="SELECT * FROM `login` where id=$uid";
                                        $qq=mysqli_query($con,$ss);
                                        $f_u=mysqli_fetch_array($qq);

echo "<script>alert('".$f_r['total']."');</script>";
extract($_POST);

 $apiKey = "rzp_test_Wi972bG7df7ltY";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="status.php?oid=<?=$oid;?>" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $f_r['total'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="SheCare"
    data-name="SheCare"
    data-description="Import Export!"
    data-prefill.name="<?php  echo $f_u['name']; ?>"
    data-prefill.email="<?php  echo $f_u['email']; ?>"
    data-prefill.contact="<?php  echo $f_u['contactno']; ?>"
    data-theme.color="#F195B2"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style type="text/css">
    .razorpay-payment-button{
        display: none;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.razorpay-payment-button').click();
    });
</script>